version: '3'


services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_DATABASE=wordpress
       - MYSQL_USER=super-secret-pwd
       - MYSQL_PASSWORD=devel
       - MYSQL_ROOT_HOST=127.0.0.1

    volumes: 
      - ./dbdata:/var/lib/mysql
      - ./my.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf'
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  wordpress:
    depends_on: 
      - db
    image: wordpress:5.1.1-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=super-secret-pwd
      - WORDPRESS_DB_PASSWORD=devel
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - app-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
    networks:
      - app-network

  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - ./wordpress:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email jomyg@gmail.com --agree-tos --no-eff-email --staging -d jomygeorge.xyz -d www.jomygeorge.xyz

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus/
    container_name: prometheus
    hostname: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    networks:
      - app-network


  prom-nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-exporter
    hostname: nginx-exporter
    restart: unless-stopped
    ports:
      - 9113:9113
    command:
      - -nginx.scrape-uri=http://webserver.ru/nginx_status
      - -nginx.ssl-verify=false
    networks:
      - app-network


  prom-os-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    container_name: node-exporter
    hostname: node-exporter
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    ports:
      - 9100:9100
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    networks:
      - app-network

  wordpress-exporter:
    container_name: wordpress-exporter
    hostname: wordpress-exporter
    image: ghcr.io/aorfanos/wordpress-exporter/wordpress-exporter:v0.0.8
    depends_on:
      - wordpress
    command:
      - -host=http://webserver.ru/index.php
      - -auth.basic=false
    ports:
      - 9112:11011
    networks:
      - app-network

  blackbox-exporter:
    container_name: blackbox-exporter
    hostname: blackbox-exporter
    image: prom/blackbox-exporter:latest
    restart: unless-stopped
    volumes:
      - ./blackbox/config.yml:/config.yml:ro
    ports:
      - "9114:9155"
    networks:
      - app-network

  victoriametrics:
    container_name: victoriametrics
    image: victoriametrics/victoria-metrics:v1.100.1
    ports:
      - 8428:8428
      - 8089:8089
      - 8089:8089/udp
      - 2003:2003
      - 2003:2003/udp
      - 4242:4242
    volumes:
      - ./vmdata:/storage
    command:
      - "--storageDataPath=/storage"
      - "--graphiteListenAddr=:2003"
      - "--opentsdbListenAddr=:4242"
      - "--httpListenAddr=:8428"
      - "--influxListenAddr=:8089"
      - "--vmalert.proxyURL=http://vmalert:8880"
      - "--retentionPeriod=2w"
    networks:
      - app-network


  # Grafana instance configured with VictoriaMetrics as datasource
  grafana:
    container_name: grafana
    image: grafana/grafana:10.3.1
    depends_on:
      - "victoriametrics"
    ports:
      - 3000:3000
    volumes:
      - ./Grafana/grafanadata:/var/lib/grafana
      - ./Grafana/provisioning/datasources/prometheus-datasource:/etc/grafana/provisioning/datasources
      - ./Grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./Grafana/dashboards/victoriametrics.json:/var/lib/grafana/dashboards/vm.json
      - ./Grafana/dashboards/vmagent.json:/var/lib/grafana/dashboards/vmagent.json
      - ./Grafana/dashboards/vmalert.json:/var/lib/grafana/dashboards/vmalert.json
    networks:
      - app-network


  


volumes:
  certbot-etc:
  wordpress:
  dbdata:
  vmdata:
  wordpress:
  nginx-conf:
  blackbox:
  Grafana:

networks:
  app-network:
    driver: bridge
